# Generated by Django 6.0.5 on 2026-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
            preserve_default=False,
        ),
    ]
