# Generated by Django 6.0.5 on 2026-07-14 17:26

from django.db import migrations

def add_default_dishes_and_labels(apps, schema_editor):
    Dish = apps.get_model('recipebook', 'Dish')
    Label = apps.get_model('recipebook', 'Label')

    # Default dishes
    dishes = ["protein", "carbohydrate", "vegetables", "complete meal", "dessert"]
    for dish_name in dishes:
        Dish.objects.get_or_create(dish_name=dish_name)

    # Default labels
    labels = ["vegan", "vegetarian", "gluten-free"]
    for label_name in labels:
        Label.objects.get_or_create(label_name=label_name)

class Migration(migrations.Migration):
    # Add any dependencies here (e.g., previous migrations)
    dependencies = [
        ("recipebook", "0002_recipe_image"),
    ]

    operations = [migrations.RunPython(add_default_dishes_and_labels)]
