# Generated by Django 6.0.5 on 2026-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0004_alter_recipeingredient_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="time_required",
        ),
    ]
