# Generated by Django 6.0.5 on 2026-07-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0005_remove_recipe_time_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="procedure",
            field=models.CharField(max_length=10000),
        ),
    ]
