# Generated by Django 6.0.5 on 2026-07-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0006_recipe_url_alter_recipe_procedure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
