# Generated by Django 6.0.5 on 2026-07-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0008_alter_recipeingredient_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=0, max_digits=6, null=True
            ),
        ),
    ]
