# Generated by Django 6.0.5 on 2026-08-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipebook", "0009_alter_recipeingredient_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MealPlan",
        ),
    ]
