# Generated by Django 6.0.5 on 2026-08-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0002_mealplan_session_key_alter_mealplan_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="just_one_day",
            field=models.BooleanField(default=False),
        ),
    ]
