# Generated by Django 6.0.5 on 2026-08-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0003_mealplan_just_one_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mealplan",
            name="just_one_day",
        ),
    ]
