# Generated by Django 6.0.5 on 2026-08-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0004_remove_mealplan_just_one_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplanrecipe",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "monday"),
                    ("Tuesday", "tuesday"),
                    ("Wednesday", "2ednesday"),
                    ("Thursday", "thursday"),
                    ("Friday", "friday"),
                    ("Saturday", "saturday"),
                    ("Sunday", "sunday"),
                    ("Today", "today"),
                ],
                default="Monday",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mealplanrecipe",
            name="meal_type",
            field=models.CharField(
                choices=[("lunch", "Lunch"), ("dinner", "Dinner")],
                default="lunch",
                max_length=10,
            ),
        ),
    ]
