# Generated by Django 6.0.5 on 2026-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0005_mealplanrecipe_day_mealplanrecipe_meal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealplan",
            name="name",
            field=models.CharField(default="Meal Plan", max_length=100),
        ),
    ]
