# Generated by Django 6.0.5 on 2026-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mealplan", "0006_mealplan_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealplan",
            name="name",
            field=models.CharField(default="Meal Plan", max_length=50),
        ),
        migrations.AlterField(
            model_name="mealplanrecipe",
            name="day",
            field=models.CharField(
                choices=[
                    ("Monday", "monday"),
                    ("Tuesday", "tuesday"),
                    ("Wednesday", "wednesday"),
                    ("Thursday", "thursday"),
                    ("Friday", "friday"),
                    ("Saturday", "saturday"),
                    ("Sunday", "sunday"),
                    ("Today", "today"),
                ],
                default="Monday",
                max_length=10,
            ),
        ),
    ]
