# Generated by Django 6.0.5 on 2026-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="user_follower",
            new_name="user_followed",
        ),
    ]
